# Generated by Django 4.1.4 on 2024-05-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountEmail', models.CharField(max_length=100)),
                ('accountPassword', models.CharField(max_length=100)),
                ('accountRole', models.CharField(choices=[('Client_Site', 'Client_Site'), ('Admin', 'Admin')], default='Client_Site', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('customerNotes', models.CharField(blank=True, max_length=200, null=True)),
                ('appointmentStatus', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDesc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFname', models.CharField(max_length=100)),
                ('customerMname', models.CharField(max_length=100)),
                ('customerLname', models.CharField(max_length=100)),
                ('customerGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('customerPhone', models.CharField(max_length=50)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=100)),
                ('supplierEmail', models.EmailField(max_length=254)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productQty', models.IntegerField()),
                ('productPrice', models.IntegerField()),
                ('productDescp', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='NecessaryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQty', models.IntegerField()),
                ('appointmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='customersName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
