# Generated by Django 5.0.6 on 2024-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_accounttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productUnit',
            field=models.CharField(default=0.00020586297760210806, max_length=100),
            preserve_default=False,
        ),
    ]
