# Generated by Django 5.0.6 on 2024-05-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountEmail', models.CharField(max_length=100)),
                ('accountPassword', models.CharField(max_length=100)),
                ('accountRole', models.CharField(choices=[('Client_Site', 'Client_Site'), ('Admin', 'Admin')], default='Client_Site', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDesc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFname', models.CharField(max_length=100)),
                ('customerMname', models.CharField(max_length=100)),
                ('customerLname', models.CharField(max_length=100)),
                ('customerGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('customerPhone', models.CharField(max_length=50)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerBirthdate', models.DateField()),
                ('customerAddress', models.CharField(max_length=500)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('accountToken', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=100)),
                ('supplierEmail', models.EmailField(max_length=254)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('appointmentCloth', models.CharField(max_length=200)),
                ('customerNotes', models.CharField(blank=True, max_length=200, null=True)),
                ('appointmentStatus', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=40)),
                ('customersName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productQty', models.IntegerField()),
                ('productUnit', models.CharField(choices=[('Pieces', 'Pieces'), ('Inches', 'Inches'), ('Meters', 'Meters'), ('Feet', 'Feet'), ('Boxes', 'Boxes'), ('Dozen', 'Dozen'), ('Yards', 'Yards'), ('Pounds', 'Pounds'), ('Bundles', 'Bundles'), ('Gallons', 'Gallons')], default='Pieces', max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDescp', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='NecessaryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQty', models.IntegerField()),
                ('appointmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
