# Generated by Django 5.0.6 on 2024-05-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supplier_supplieraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Supply',
        ),
    ]
