# Generated by Django 5.0.6 on 2024-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_productunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productUnit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Inches', 'Inches'), ('Meters', 'Meters'), ('Feet', 'Feet'), ('Boxes', 'Boxes'), ('Dozen', 'Dozen'), ('Yards', 'Yards'), ('Pounds', 'Pounds'), ('Bundles', 'Bundles'), ('Gallons', 'Gallons')], default='Pieces', max_length=100),
        ),
    ]
