# Generated by Django 5.0.6 on 2024-05-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_product_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesPrice', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('servicesName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supply')),
            ],
        ),
    ]
