# Generated by Django 5.0.6 on 2024-05-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_services_servicesname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentCloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services'),
        ),
    ]
