# Generated by Django 5.0.6 on 2024-05-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appointment_appointmentcloth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentCloth',
            new_name='appointmentServices',
        ),
    ]
