# Generated by Django 5.0.6 on 2024-05-18 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_appointmentcloth_appointment_appointmentservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='servicesSchool',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
