# Generated by Django 5.0.6 on 2024-05-18 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_services_servicesschool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='servicesName',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='servicesSchool',
            new_name='productSchool',
        ),
        migrations.AddField(
            model_name='services',
            name='productSize',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
