# Generated by Django 5.0.6 on 2024-05-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_servicesname_services_productname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='productName',
            new_name='servicesOffered',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='productSchool',
            new_name='servicesSchool',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='productSize',
            new_name='servicesSize',
        ),
    ]
