# Generated by Django 5.0.6 on 2024-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_appointmentqty_services_clothnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentQty',
            field=models.IntegerField(),
        ),
    ]
