# Generated by Django 5.0.6 on 2024-05-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_appointment_appointmentqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
                ('userFeedback', models.CharField(max_length=100)),
                ('appointmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
            ],
        ),
    ]
