# Generated by Django 5.0.6 on 2024-05-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appointmentquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='clothSize',
        ),
    ]
